### ISSUE TITLE
FsLab Nuget: Json .NET dependencies

### ISSUE THREAD

**Issue by colinbull** [fslaborg/FsLab#92]
When adding the FsLab nuget package, using `Manage Nuget packages` it fails to resolve Json.net due to conflicting dependencies.

![image](https://cloud.githubusercontent.com/assets/585546/8500768/2638d108-2197-11e5-8893-40bfe74db3cf.png)

Note: that paket successfully manages this.

**Comment by forki** [comment]
I assume it's similar to https://github.com/fsprojects/Paket/issues/905 where @eiriktsarpalis and @mathias-brandewinder reported a config that seems to be valid, but nuget's resolver is not finding a resolution.

**Comment by colinbull** [comment]
Yes, exactly that..

**Comment by forki** [comment]
I think NuGet just pins versions to early in the reesolver then fails to use JSON 6.08 later. 
In Paket we do backtracking and search the complete search tree: http://fsprojects.github.io/Paket/resolver.html

Since I don't see the nuget people fix that soon, we should move the dependency to Newtonsoft.Json the top (I know that's a bit stupid but it could actually trick the nuget resolver).

**Comment by forki** [comment]
The interesting thing is: FsLab is pinning all direct dependencies to concrete versions in its nuspec file and it's still breaking the nuget resolver.

**Comment by maartenba** [comment]
@yishaigalatzer that is

**Comment by yishaigalatzer** [comment]
You shouldn't be pinning specific versions, that's always a bad practice. Can you try nuget from vs2015? We do have backtracking, the build is available on codeplex (on vacation from my phone so can't dice deeper)

**Comment by forki** [comment]
There is a valid resolution and now it's bad practice?

**Comment by yishaigalatzer** [comment]
@forki are you all about picking fights?

**Comment by yishaigalatzer** [comment]
Finally back at my computer. Yes definitely a bad practice, and you will not always find a resolution.

In general the rule of thumb is to never pick a specific version of a package, and never do that if you down own the dependency.

Example here:

Package fslab depends directly on newtonsoft.json 6.08 and only that version

Now another package is consumed in the same project that depends on a bug fix or a new feature in 7.0.1. Although fslab in practice is not broken by using 7.01, there is now way for the two packages to co-exist in the same project.

In NuGet 3.1 (using project.json) we are letting the project owner a way to resolve this and pick the version directly, but there is no mathematical solution to the problem.

Similarly you rarely want to do a version cap (although there are some legitimate cases, when a newer version is known to break your package you might want to ship one with a version cap, and another that deals with the breaking change).

Hope that clarifies the situation.

**Comment by tpetricek** [comment]
We need to pin versions when you're using things via NuGet (not a problem with Paket), because we also want to provide a nice load script for F# Script file users. The file is auto-generated, but you can see the last snapshot here: https://github.com/fslaborg/FsLab/blob/master/src/FsLab.fsx

Because NuGet puts the version number in the directory, we need a fixed version - otherwise we cannot give people a single load script and they'd have to write that crazy 50 lines of references by hand :-(.

So, either NuGet needs to avoid putting version numbers in directory names, or we need to stick to a fixed version reference (or F# itself needs to add some fancy workaround for this..)

**Comment by tpetricek** [comment]
@colinbull In the meantime, download the "FsLab basic template" from http://fslab.org/download/. This is using Paket and it should work :-)

**Comment by tpetricek** [comment]
Well, I released a new version of FsLab, which references the most recent JSON.NET release, so that should make it work until JSON.NET has a new release. They only have one every couple of months.... :-/

**Comment by yishaigalatzer** [comment]
This is still very wrong, you are now blocking pre-releases from being used. you should instead just have a >= 6.0.8 dependency instead of an = dependency.

**Comment by yishaigalatzer** [comment]
This is also true for all other dependencies, if this package is meant to be consumed with more packages in the solution it is creating a high probability of conflicts.

I did forget to mention another rule - You always want to pick the minimal dependency your package can work with to prevent collisions. So for example if you can work with newtonsoft.json 6.0.4 and also with 6.0.8 then the dependency should look like >= 6.0.4. The more you constraint the dependencies the more issues are going to block it from co-existing with other packages.

**Comment by davidfowl** [comment]
Exact version matches are generally a bad practice a they stop other packages from working. Even if packet does backtracking in order to find a path that "works" doesn't make it correct. Is there any specific reason why JSON.NET 6.0.8 is specified as an exact version? Is it broken with 6.0.9?

**Comment by yishaigalatzer** [comment]
There is no 6.0.9 :) but there is a 7.01 (which now the new package have an = relationship with)

**Comment by tpetricek** [comment]
@yishaigalatzer @davidfowl I understand what you're saying, but there is no way to make non-fixed package references actually work with NuGet and F# Script file scenario. Does my explanation above make sense?

To understand what's going on here, please try the following:

 - Open VS and create new "F# Tutorial" project. This creates project with `Tutorial.fsx`

 - Add NuGet reference to FsLab

 - Delete everything in `Tutorial.fsx` and instead put in:

        #load @"packages\FsLab.0.3.3\FsLab.fsx"
        open XPlot.GoogleCharts
        open FSharp.Data

        let wb = WorldBankData.GetDataContext()
        wb.Countries.Greece.Indicators.``GDP (current US$)`` |> Chart.Line

 - Select the code, hit Alt+Enter (or right click and choose Execute in F# Interactive)

Now, have a look at the contents of the `FsLab.fsx` file. Because NuGet puts version number in the folder name, this can *only* work when we know the exact version (the `FsLab.fsx` file needs to know what the directory name is!)

I hope this explains why `>=` dependency would not work for FsLab. Does that make sense? The F# script workflow is different than C# workflow, so feel free to ask if you need more information.

I'm more than happy to use a better solution, but it needs to actually _work_. So, if you can suggest some alternative, that would be great.

**Comment by colinbull** [comment]
O.K at this point I'm kind of confused as to why it should matter if we have pinned dependencies or not. As there is in general no analytical solution to this as @yishaigalatzer points out, so why even try. If the user has a working version by pinning those dependencies don't second guess, just accept it. That is after all the point of allowing users to supply constraints? Right?

**Comment by tpetricek** [comment]
One more clarification - you shouldn't think of FsLab as a .NET library. If you were building libraries or applications, you'd add references directly to the individual packages. What FsLab is trying to do is to give one easy to reference (and load from F# script file) package that gives you the latest versions of everything.

**Comment by yishaigalatzer** [comment]
The complaint here is about installing it into a project. How can you control what other references are in a project? If this is just about loading this single package and never something else this could work if you properly tested it. But if someone tries to update to a prerelase of one of the dependencies it is broken.

Hence I would err to the side of >= rather than = when defining dependencies

**Comment by tpetricek** [comment]
Of course the complaint is about installing it into a project. In Visual Studio, you cannot install a package _without a project_. I'll let @colinbull answer whether his intend use was through `#load` and script files or as references in a compiled project though.

In any case, the script file scenario that I described above is the primary scenario that we want to support in FsLab. And I'm not changing `=` to `>=` if it breaks our primary scenario (which would be the case at the moment).

I'm open to suggestions how to do things better, but please go through the primary scenario (described in my long comment above) to understand what we're trying to do. You can also watch 15 minutes of [this video](https://channel9.msdn.com/posts/Understanding-the-World-with-F), which shows the use case.

**Comment by yishaigalatzer** [comment]
I get what you are doing a bit better now. I don't quite get why it should break but it might be because of resolved deficiencies in nuget 2.x I'm hoping nuget 3 resolved it and definitely using project.json will, but its not yet ready for Fs though. Update I would be better I hope.

**Comment by forki** [comment]
@tpetricek why did you close this one?

**Comment by tpetricek** [comment]
The way to workaround this is to do a new FsLab release every time new version of JSON.NET is released - and I've done this already. 

Aside from that, we recommend people to use Paket (and now all templates do that), which is able to resolve fixed-version dependencies just fine.
